friendly_notes/friendly_notes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('note.urls')),
]

friendly_notes/note/urls.py
from django.views.generic import TemplateView
from django.urls import path

from note import views


app_name = 'note'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddNoteView.as_view(), name='add'),
    path('get/<int:pk>/', views.GetNoteView.as_view(), name='get'),
    path('random/', views.random_note, name='random'),
]

friendly_notes/note/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _

from note.lexer_choices import ALL_LEXER_CHOICES


class Note(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name=_('title')
    )
    content = models.TextField(verbose_name=_('content'))
    date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('date')
    )
    language = models.CharField(
        choices=ALL_LEXER_CHOICES,
        max_length=21,
        blank=True,
        verbose_name=_('language')
    )

    class Meta:
        verbose_name = _('note')
        verbose_name_plural = _('notes')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('note:get', kwargs={'pk': self.pk})

friendly_notes/user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

friendly_notes/note/forms.py
from django import forms
from captcha.fields import CaptchaField

from note.models import Note


class NoteForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Note
        exclude = ['date']

friendly_notes/note/views.py
from random import choice

from django.views import generic
from django.urls import reverse
from django.shortcuts import redirect, render

from note.models import Note
from note.forms import NoteForm


class IndexView(generic.TemplateView):
    template_name = 'note/index.html'


class AddNoteView(generic.CreateView):
    form_class = NoteForm
    template_name = 'note/add_note.html'


class GetNoteView(generic.DetailView):
    model = Note
    template_name = 'note/get_note.html'


def random_note(request):
    pk_list = Note.objects.all().values_list('pk', flat=True)

    if pk_list:
        random_pk = choice(pk_list)
        return redirect('note:get', pk=random_pk)

    url = reverse('note:add')
    return render(request, 'note/no_notes.html', {'url': url})

friendly_notes/user/views.py
from django.shortcuts import render

# Create your views here.

friendly_notes/note/templates/note/add_note.html
{% extends 'shared/layout.html' %}
{% load static i18n %}

{% block title %}
{% translate 'Add a note' %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'note/css/add_note.css' %}" />
{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="{% translate 'Add' %}" />
</form>
{% endblock %}

friendly_notes/note/templates/note/get_note.html
{% extends 'shared/layout.html' %}
{% load static i18n pygmentify_tags %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% pygmentify_css %}" />
<link rel="stylesheet" href="{% static 'note/css/code.css' %}" />
{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>
<i>{% translate 'Created on' %} {{ object.date | date }}</i>
<br />

{% pygmentify %}
<pre lang="{{ object.language }}">
  {{ object.content }}
</pre>
{% endpygmentify %}

{% endblock %}

friendly_notes/note/templates/note/index.html
{% extends 'shared/layout.html' %}
{% load static i18n %}

{% block title %}
{% translate 'Index' %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'note/css/index.css' %}" />
{% endblock %}

{% block content %}
<h2>
  {% translate 'Welcome to Friendly Notes!' %}
</h2>
<p>
  {% blocktranslate %}
  This is an anonymous service that lets you paste 
  and share code / text. These pastes are called <b>notes</b>.
  {% endblocktranslate %}
</p>
<p>
  {% translate 'Above you can see three links:' %}
  <ol class="index-list">
    <li>
      {% translate 'Main Page' %} - {% translate "the page you're currently reading." %}
    </li>
    <li>
      {% translate 'Add a Note' %} - {% translate 'here you can, well, add a note.' %}
    </li>
    <li>
      {% translate 'Random Note' %} - {% translate 'a random note that has been posted.' %}
    </li>
  </ol>
</p>
<p>
  {% blocktranslate %}
  Possibly, there will be a REST API in the future, so that
  you'll be able to add notes without even visiting this site.
  {% endblocktranslate %}
</p>
{% endblock %}

friendly_notes/note/templates/note/no_notes.html
{% extends 'shared/layout.html' %}
{% load static i18n %}

{% block title %}
{% translate 'No notes' %}
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
<p>
  {% blocktranslate %}
  There are no notes on this Friendly Notes instance!
  Go <a href="{{ url }}">add one</a>.
  {% endblocktranslate %}
</p>
{% endblock %}

friendly_notes/templates/shared/layout.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="{% translate 'en' %}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'shared/css/layout.css' %}" />
    <link rel="stylesheet" href="{% static 'shared/css/navbar.css' %}" />
    <link 
      href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
      rel="stylesheet"
    />
    {% block css %}{% endblock %}
    <title>
      {% block title %}{% endblock %} - Friendly Notes
    </title>
  </head>
  <body>
    {% include 'shared/navbar.html' %}
    <main class="container">
      {% block content %}{% endblock %}
    </main>
    <footer>
      {% translate 'This website on <a href="//github.com/karmek-k/friendly-notes">GitHub</a>' %}
    </footer>
  </body>
</html>

friendly_notes/templates/shared/navbar.html
{% load i18n %}

<nav class="navbar">
  <h1>
    <a href="{% url 'note:index' %}">
      Friendly Notes
    </a>
  </h1>
  <ul>
    <li>
      <a href="{% url 'note:index' %}">
        {% translate 'Main Page' %}
      </a>
    </li>
    <li>
      <a href="{% url 'note:add' %}">
        {% translate 'Add a Note' %}
      </a>
    </li>
    <li>
      <a href="{% url 'note:random' %}">
        {% translate 'Random Note' %}
      </a>
    </li>
  </ul>
</nav>